linters:
  # Necessary configuration for dealing with Reddit
  IdSelector:
    enabled: false

  QualifyingElement:
    enabled: false

  NestingDepth:
    enabled: false # In case hacks are needed for functionality needing lots of selectors

  SelectorDepth:
    enabled: false # Same reason as disabling NestingDepth

  ImportantRule:
    enabled: false

  SelectorFormat:
    enabled: false

  # URL formats not linted because of the format
  UrlFormat:
    enabled: false

  UrlQuotes:
    enabled: false

  # Placeholder extends turned off so the current SVG > PNG sprite build system can work
  PlaceholderInExtend:
    enabled: false

  # Custom preferences
  ColorKeyword:
    enabled: false

  ColorVariable:
    enabled: false

  ElsePlacement:
    style: 'new_line'

  MergeableSelector:
    enabled: false

  PropertySortOrder:
    order:
      - content
      - smacss

  StringQuotes:
    style: 'double_quotes'
